apiVersion: apps/v1
kind: Deployment
metadata:
  name: personedit-appserver
spec:
  selector:
    matchLabels:
      app: personedit-appserver
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: personedit-appserver
    spec:
      containers:
      - name: personedit-appserver
        image: rockylhotka/appserver:20181115050628
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: personedit-appserver
spec:
  selector:
    app: personedit-appserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer